//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusrGalimulin
{
    using System;
    using System.Collections.Generic;
    
    public partial class USerService
    {
        public Nullable<int> Сотрудники { get; set; }
        public Nullable<int> Список_услуг_сотрудников { get; set; }
        public int id { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual USerService USerService1 { get; set; }
        public virtual USerService USerService2 { get; set; }
        public virtual User User { get; set; }
    }
}
